### ISSUE TITLE
Please add ingress

### ISSUE THREAD

**Issue by TJM** [PureStorage-OpenConnect/pso-explorer#13]
We do not have load balancer integration on our internal clusters, instead we usually use ingress (nginx). Most helm charts have the same ingress template.  We will look into adding it too.

**Comment by dnix101** [comment]
@TJM Have you been able to get ingress working? There was a small issue with ingress and HTTPS which has been resolved today with the release of v0.5.5. If you want, feel free to open a PR to add ingress to the Helm chart.

**Comment by mscbpi** [comment]
v0.5.5  does not seem to help having a working https ingress (hard reference to http in the code)

**Comment by dnix101** [comment]
@mscbpi I think I have fixed the last full references by changing them to relative links (Laravel generates full URL's by default). If you'd be willing you could try the development build `v0.5.5a-devel` which should run correctly behind https ingress I believe.

**Comment by mscbpi** [comment]
@dnix101  sorry I was wrong: using `v0.5.4` despite of upgrading the chart, because version was hardcoded in the `values.yaml` I use.
https works with `v0.5.5` however settings/PSO page returns 500 Server Error (works with `v0.5.4`), no logs. Works again with `v0.5.5a-devel`

Using latest `pso v6.0.2` version.

**Comment by dnix101** [comment]
@mscbpi thanks for the update. In the meanwhile the helm chart and container image have been updated to 0.5.5a which fixes the 500 server error. The image tag to use for your `values.yaml` is v0.5.5a.

**Comment by dnix101** [comment]
@mscbpi thanks for the update. In the meanwhile the helm chart and container image have been updated to 0.5.5a which fixes the 500 server error. The image tag to use for your `values.yaml` is v0.5.5a.

**Comment by TJM** [comment]
Sorry, I got sidetracked into another project (artifactory upgrades)... I do still want to see ingress on this :)

**Comment by dnix101** [comment]
@TJM good news, I'm working on this in branch ingress. Just need to test a bit more before I merge.

**Comment by dnix101** [comment]
@TJM the new release v0.5.6 now includes the ingress definitions which can be enabled using the Helm Chart / values.yaml.
