### ISSUE TITLE
run as non-root user

### ISSUE THREAD

**Issue by aboje** [PureStorage-OpenConnect/pso-explorer#18]
Can you set an option to run the pods as non-root users? If we implement the podsecuritypolicy runAsUser rule "MustRunAsNonRoot", the pods won't start. 

Error: container has runAsNonRoot and image will run as root

**Comment by dnix101** [comment]
@aboje I was able to reproduce this. The issue is that the `redis:alpine` container runs as root by default, since no USER parameter is specified in the Dockerfile. I've just created a new branch [`non-root`](https://github.com/PureStorage-OpenConnect/pso-explorer/tree/non-root) where I've added a securityContext with user id 1001 for the Redis container. Can you test this and let me know if that works for you?

**Comment by aboje** [comment]
I ran the following but I don't see the updates to the deployment. I do see them in your deployment template online, however, so I'm guessing I'm not upgrading from the non-root branch correctly. 
helm repo add pso-explorer 'https://raw.githubusercontent.com/PureStorage-OpenConnect/pso-explorer/non-root'
helm upgrade pso-explorer -f pso-explorer.values -n pso-explorer pso-explorer/pso-explorer

**Comment by dnix101** [comment]
@aboje I don't think that will work indeed, since Helm doesn't allow you to add a GitHub branch as repo. You'd have to clone the repo and install from the cloned repo:

```
git clone -b non-root https://github.com/PureStorage-OpenConnect/pso-explorer.git
cd pso-explorer
helm upgrade pso-explorer -f pso-explorer.values -n pso-explorer .
```

By specifying `.` instead of `pso-explorer/pso-explorer` you're installing from the local cloned repo.

**Comment by aboje** [comment]
Got it, thank you. I installed as you wrote. Works great. pso-explorer starts successfully and it using my restricted psp policy. I can still get into the UI without problems. Thanks for the fast response.

**Comment by sdodsley** [comment]
@aboje are you willing to share the psp policy?

**Comment by dnix101** [comment]
Perfect, great to hear it works. I'll make sure to merge this in the new release!
