### ISSUE TITLE
Flashblade not recognized

### ISSUE THREAD

**Issue by mscbpi** [PureStorage-OpenConnect/pso-explorer#5]
It reports the FB as offline while it is working correctly

![image](https://user-images.githubusercontent.com/28528210/87914377-d6f8d100-ca70-11ea-85d1-ba8070f6b062.png)

NfsEndPoint is set:

![image](https://user-images.githubusercontent.com/28528210/87914463-f42d9f80-ca70-11ea-9c3a-820fb96e5e14.png)

**Comment by dnix101** [comment]
@mscbpi The `values.yaml` settings are case sensitive and the NFS Endpoint should be configured as `NFSEndPoint`

**Comment by mscbpi** [comment]
Thanks !

The PSO is working correctly as-is (NfsEndPoint) and it used to be documented as-is... and this syntax is still visible there for example:

https://github.com/purestorage/helm-charts/blob/master/operator-csi-plugin/values.yaml

**Comment by dnix101** [comment]
Yes, it used to be NfsEndPoint, this was changed in 2019. Newer versions will no longer accept NfsEndPoint, which is why PSO Explorer shows the error. Thanks for the comment on the example, I just opened a PR to change it to NFSEndPoint.

**Comment by dnix101** [comment]
@mscbpi the latest devel build now shows the FlashBlade and just shows a warning if NfsEndPoint is used. This will also be part of the upcoming 0.5.3 release.
